class: sifter
name: device_exposure_omop_to_fhir
outdir: ../output

config:
  device_exposure:  ../data_used/redivis_device_exposure.json
  schema: ../iceberg/schemas/bmeg/
  conceptData: ../data_used/MASTER_CONCEPT_TABLE_MODIFIED.json

inputs:
  Device_Exposure_Data:
    plugin:
      commandLine: python3 epochtime_convert.py {{config.device_exposure}} Device_Exposure
  
  conceptTheta:
    jsonLoad:
      input: "{{config.conceptData}}"
  
pipelines:
  conceptTable:
    - from: conceptTheta
    - map:
        method: fix
        gpython: |
          def fix(row):
            return {
              "concept_id": str(row["concept_id"]),
              "vocabulary_id": str(row["vocabulary_id"]),
              "concept_name": str(row["concept_name"]),
              "concept_code": str(row["concept_code"])
            }

  Procedure:
    - from: Device_Exposure_Data
    - uuid:
        value: "{{row.device_exposure_id}}"
        field: id
        namespace: 'aced-idp.org' 
    - uuid:
        value: "{{row.person_id}}"
        field: person_id_uuid
        namespace: 'aced-idp.org'
    - uuid:
        value: "{{row.visit_occurrence_id}}"
        field: visit_occurrence_id_uuid
        namespace: 'aced-idp.org'


    - map:
        method: cast
        gpython: |
          def cast(row):
            row["device_concept_id"] = str(int(row["device_concept_id"]))
            row["device_type_concept_id"] = str(int(row["device_type_concept_id"]))
            return row

    - lookup:
        pipeline:
          from: conceptTable
          key: concept_id
        lookup: "{{row.device_concept_id}}"
        copy: 
          CONCEPT_ID_NAME: concept_name
          CONCEPT_ID_CODE: concept_code
          CONCEPT_VOCAB_ID: vocabulary_id
    
    - lookup:
        pipeline:
          from: conceptTable
          key: concept_id
        lookup: "{{row.device_type_concept_id}}"
        copy: 
          CONCEPT_TYPE_ID_NAME: concept_name
          CONCEPT_TYPE_ID_CODE: concept_code
          CONCEPT_TYPE_VOCAB_ID: vocabulary_id

    - map:
        method: fix
        gpython: | 
          def is_int(num):
              try:
                int(num)
                return True
              except ValueError:
                return False

          def fix(row):
            vocab_code_to_display = {
              "NUCC": "https://www.nucc.org/",
              "CMS Place of Service": "https://www.cms.gov/Medicare/Coding/place-of-service-codes",
              "SNOMED":"http://snomed.info/sct/",
              "LOINC": "https://loinc.org/",
              "Visit": "https://athena.ohdsi.org/search-terms/terms/",
              "Type Concept": "https://athena.ohdsi.org/search-terms/terms/",
              "ICD9CM": "https://www.cms.gov/Medicare/Coding/ICD9ProviderDiagnosticCodes/codes",
              "ICD10CM": "https://icd10cmtool.cdc.gov/",
              "SOPT": "https://www.nahdo.org/sopt",
              "Relationship": "https://athena.ohdsi.org/search-terms/terms/",
              "Vocabulary": "https://athena.ohdsi.org/search-terms/terms/",
              "UCUM": "https://ucum.org/",
              "MeSH": "https://www.nlm.nih.gov/research/umls/licensedcontent/umlsknowledgesources.html",
              "NDFRT": 'https://www.nlm.nih.gov/research/umls/rxnorm/docs/rxnormfiles.html',
              "Condition Type": "https://athena.ohdsi.org/search-terms/terms/",
              "NDC": "https://www.nlm.nih.gov/research/umls/rxnorm/docs/rxnormfiles.html",
              "RxNorm": "https://www.nlm.nih.gov/research/umls/rxnorm/docs/rxnormfiles.html",
              "RxNorm Extension": "https://www.nlm.nih.gov/research/umls/rxnorm/docs/rxnormfiles.html", #note sure about this one
              "Observation Type": "https://athena.ohdsi.org/search-terms/terms/",
              "None": "https://athena.ohdsi.org/search-terms/terms/",
              "CPT4": "https://www.nlm.nih.gov/research/umls/licensedcontent/umlsknowledgesources.html",
              "ICD9Proc": "https://www.cms.gov/Medicare/Coding/ICD9ProviderDiagnosticCodes/codes",
              "Procedure Type": "https://athena.ohdsi.org/search-terms/terms/",
              "HCPCS" : "https://www.nlm.nih.gov/research/umls/licensedcontent/umlsknowledgesources.html",
              "Device Type": "https://athena.ohdsi.org/search-terms/terms/",
            }

            out = {
              "id": str(row["id"]),
              "identifier": [{ 
                "system": "https://redivis.com/datasets/ye2v-6skh7wdr7/tables",
                "value": "MedicationStatement/" + str(row["device_exposure_id"])
              },
              {
                "system": "https://redivis.com/datasets/ye2v-6skh7wdr7/tables",
                "value": "Patient/" + str(row["person_id"])
              }],
              "resourceType":"Procedure",
              "status": "completed",
              "subject": {"reference":"Patient/" + str(row["person_id_uuid"])},
              "code":{
                "coding":[{
                  "system": vocab_code_to_display[str(row["CONCEPT_VOCAB_ID"])],
                  "display": str(row["CONCEPT_ID_NAME"]),
                  "code": str(row["CONCEPT_ID_CODE"])
                }],
                "text": str(row["CONCEPT_ID_NAME"]),
              },
              "occurrencePeriod": 
                {
                  "start": row["device_exposure_start_date"],
                  "end": row["device_exposure_end_date"]
                },
              # TODO don't hardcode this first entry base it off? what field?
              "category":[{
                "coding":[{
                  "code": "103693007",
                  "display": "Diagnostic procedure",
                  "system":"http://hl7.org/fhir/ValueSet/procedure-category"
                },
                {
                  "code": str(row["CONCEPT_TYPE_ID_CODE"]),
                  "display": str(row["CONCEPT_TYPE_ID_NAME"]),
                  "system": vocab_code_to_display[str(row["CONCEPT_TYPE_VOCAB_ID"])]
                }],
                "text": str(row["CONCEPT_TYPE_ID_NAME"]),
              }]
            }
            
            if "device_exposure_start_datetime" in row and row["device_exposure_start_datetime"] is not None:
              out["occurrencePeriod"]["start"] =  row["device_exposure_start_datetime"]
            if "device_exposure_end_datetime" in row and row["device_exposure_end_datetime"] is not None:
              out["occurrencePeriod"]["end"] = row["device_exposure_end_datetime"]
            
            # this should be a codeable concept it's just that I don't think there is an appropriate
            # place to put it in a codeable concept slot in FHIR
            if (("device_source_value" in row and row["device_source_value"] is not None) or\
               ("quantity" in row and row["quantity"] is not None) or\
               ("procedure_source_value" in row and row["procedure_source_value"] is not None) or\
               ("unique_device_id" in row and row["unique_device_id"] is not None)):  
              out["extension"] = []
              if " device_source_value " in row and row[" device_source_value "] is not None:
                out["extension"].append({
                  "url": "unsure",
                  "value": row[" device_source_value "]
                })
              if "quantity" in row and row["quantity"] is not None:
                out["extension"].append({
                  "url": "not idea",
                  "value": row["quantity"]
                })
              if "procedure_source_value" in row and row["procedure_source_value"] is not None:
                out["extension"].append({
                  "value": row["procedure_source_value"],
                  "url":"unsure"
                })
              if "unique_device_id " in row and row["unique_device_id "] is not None:
                out["extension"].append({
                  "url": "not sure",
                  "value": row["unique_device_id "]
                })

            if "provider_id" in row and row["provider_id"] is not None:
                out["performer"] = [{"actor":{"reference":"Practitioner/" + str(row["provider_id"])}}]
             
            if "visit_occurrence_id_uuid" in row and row["visit_occurrence_id_uuid"] is not None:
              out["encounter"] = {"reference":"Encounter/" + str(row["visit_occurrence_id_uuid"])}
              out["identifier"].append(
               {
                "system": "https://redivis.com/datasets/ye2v-6skh7wdr7/tables",
                "value": "Encounter/" + str(row["visit_occurrence_id"])
               })
            
            #  PROPERTY visit_detail_id:  like drug_exposure_omop_to_fhir.yaml not sure what to do with this 
            # property just yet. Need to look at FHIR Encounter and OMOP visit detail see where it would hook in

            if "device_source_concept_id" in row and row["device_source_concept_id"] is not None:
              out["extension"] = []
              out["extension"].append({
                "url":"not sure",
                "valueString": str(row["device_source_concept_id"])
              })

            return out
            
    # procedure not in iceberg at the moment
    #- objectValidate:
        #schema: "{{config.schema}}"
        #title: Procedure
        
    #- debug: {}
    - emit:
        name: Procedure

