
class: sifter
name: observation_omop_to_fhir

outdir: ../output

config:
  schema: ../iceberg/schemas/bmeg/
  observation_file: ../data_used/mimic-iv_observation.json #../data_used/Eunomia_observation.json
  conceptData: ../data_used/MASTER_CONCEPT_TABLE_MODIFIED.json

inputs:
  observation_Data:
    plugin:
       commandLine: python3 epochtime_convert.py {{config.observation_file}} Observation
    
  conceptData:
    jsonLoad:
      input: "{{config.conceptData}}"

pipelines:
  conceptTable:
    - from: conceptData
    - map:
        method: fix
        gpython: |
          def fix(row):
            return {
              "concept_id": str(row["concept_id"]),
              "vocabulary_id": str(row["vocabulary_id"]),
              "concept_code": str(row["concept_code"]),
              "concept_class_id": str(row["concept_class_id"]),
              "concept_name": str(row["concept_name"])
            }

  observation:
    - from: observation_Data
    - uuid:
        value: "{{row.id}}"
        field: id
        namespace: 'aced-idp.org'
    - uuid:
        value: "{{row.PERSON_ID}}"
        field: patient_id
        namespace: 'aced-idp.org'
    - uuid:
        value: "{{row.VISIT_OCCURRENCE_ID}}"
        field: encounter_id
        namespace: 'aced-idp.org'
    - uuid:
        value: "{{row.PROVIDER_ID}}"
        field: practitioner_id
        namespace: 'aced-idp.org'
    - uuid:
        value: "{{row.VISIT_DETAIL_ID}}"
        field: visit_detail_id
        namespace: 'aced-idp.org'

    - lookup:
        pipeline:
          from: conceptTable
          key: concept_id
        lookup: "{{row.OBSERVATION_CONCEPT_ID}}"
        copy: 
          NEW_VOCABULARY_ID: vocabulary_id
          CONCEPT_CODE: concept_code
          CODE_CONCEPT_NAME: concept_name
          CONCEPT_CLASS: concept_class_id
             
    - lookup:
        pipeline:
          from: conceptTable
          key: concept_id
        lookup: "{{row.OBSERVATION_TYPE_CONCEPT_ID}}"
        copy: 
          VOCABULARY_TYPE_CONCEPT_ID: vocabulary_id
          TYPE_CONCEPT_ID_NAME: concept_name
          TYPE_CONCEPT_ID_CODE: concept_code
    
    - lookup:
        pipeline:
          from: conceptTable
          key: concept_id
        lookup: "{{row.OBSERVATION_SOURCE_CONCEPT_ID}}"
        copy: 
          VOCABULARY_SOURCE_CONCEPT_ID: vocabulary_id
          SOURCE_CONCEPT_CLASS: concept_class_id
          CONCEPT_NAME: concept_name
          SOURCE_CONCEPT_CODE: concept_code

    # source concept IDS should be extensions because they hold the ID and not the code
    # so it doesn't make sense for them to be codeable concepts
    - map:
        method: populate_observation
        gpython : |
          def is_int(num):
            try:
              int(num)
              return True
            except ValueError:
              return False
          
          def populate_observation(row):
            if "CONCEPT_CODE" not in row:
              print(row["OBSERVATION_CONCEPT_ID"])
              return
            
            vocab_code_to_display = {
              "NUCC": "https://www.nucc.org/",
              "CMS Place of Service": "https://www.cms.gov/Medicare/Coding/place-of-service-codes",
              "SNOMED":"http://snomed.info/sct/",
              "LOINC": "https://loinc.org/",
              "Visit": "https://athena.ohdsi.org/search-terms/terms/",
              "Type Concept": "https://athena.ohdsi.org/search-terms/terms/",
              "ICD9CM": "https://www.cms.gov/Medicare/Coding/ICD9ProviderDiagnosticCodes/codes",
              "ICD10CM": "https://icd10cmtool.cdc.gov/",
              "SOPT": "https://www.nahdo.org/sopt",
              "Relationship": "https://athena.ohdsi.org/search-terms/terms/",
              "Vocabulary": "https://athena.ohdsi.org/search-terms/terms/",
              "UCUM": "https://ucum.org/",
              "MeSH": "https://www.nlm.nih.gov/research/umls/licensedcontent/umlsknowledgesources.html",
              "NDFRT": 'https://www.nlm.nih.gov/research/umls/rxnorm/docs/rxnormfiles.html',
              "Condition Type": "https://athena.ohdsi.org/search-terms/terms/",
              "NDC": "https://www.nlm.nih.gov/research/umls/rxnorm/docs/rxnormfiles.html",
              "RxNorm": "https://www.nlm.nih.gov/research/umls/rxnorm/docs/rxnormfiles.html",
              "RxNorm Extension": "https://www.nlm.nih.gov/research/umls/rxnorm/docs/rxnormfiles.html", #note sure about this one
              "Observation Type": "https://athena.ohdsi.org/search-terms/terms/",
              "None":"None",
              "HCPCS": "https://www.nlm.nih.gov/research/umls/licensedcontent/umlsknowledgesources.html"
            }

            # this doesn't seem right might be better to drop this mapping / field or rework it entirely
            observation_concept_class_mapper = {
              "Context-dependent":"survey", # <-- what would you even put for context dependant? 
              "Clinical Finding": "exam",
              "Morph Abnormality": "exam",
              "Event": "exam",
              "HCPCS": "survey", # <-- not sure about this one
              "5-dig billing code": "survey",
              "4-dig nonbill V code": "survey",
              "Clinical Observation": "exam",
              "Observable Entity": "exam",
              "Qualifier Value": "?",
              "Survey": "survey",
              "Procedure": "procedure",
              "Location": "survey",
            }

            items = [val for val in row.items() if val[1] is not None]
            required_fields = ["OBSERVATION_ID", "PERSON_ID", "OBSERVATION_CONCEPT_ID", "OBSERVATION_DATE", "observation_type_concept_id"]      
            # This if below might need to get deleted
            if (is_int(row["CONCEPT_CODE"])):
              row["CONCEPT_CODE"] = int(row["CONCEPT_CODE"])
            assert(not all(item in items for item in required_fields)),"Error, not all required fields are present in OMOP structures"
            out = {
              "id": row["id"],
              "identifier": [{ 
                "system": "https://github.com/OHDSI/Eunomia",
                "value": "Observation/" + str(row["OBSERVATION_ID"])
              },
              {
                "system": "https://github.com/OHDSI/Eunomia",
                "value": "Patient/" + str(row["PERSON_ID"])
              }],
              "status": "final",
              "effectiveDateTime": str(row["OBSERVATION_DATE"]),
              "resourceType": "Observation",
              "subject": {"reference": "Patient/" + str(row["patient_id"])},
              "code":{
                "coding":[{
                  "system":  str(vocab_code_to_display[row["NEW_VOCABULARY_ID"]]),
                  "code": str(row["CONCEPT_CODE"]),
                  "display": str(row["CODE_CONCEPT_NAME"])
                }],
                "text": str(row["CODE_CONCEPT_NAME"])
              },
              "category":[{
                "coding":[{
                  "system": str(vocab_code_to_display[row["VOCABULARY_TYPE_CONCEPT_ID"]]),
                  "code": str(row["TYPE_CONCEPT_ID_CODE"]),
                  "display": str(row["TYPE_CONCEPT_ID_NAME"])
                }
               ],
                "text": "Observation Type",
              }],
              "extension": [],
            }

            if "OBSERVATION_CONCEPT_ID" in row and row["OBSERVATION_CONCEPT_ID"] is not None and row["OBSERVATION_CONCEPT_ID"] != "0":
              out["category"][0]["coding"].append({
                  "system": "http://hl7.org/fhir/ValueSet/observation-category",
                  "code": observation_concept_class_mapper[row["CONCEPT_CLASS"]],
                  "display": observation_concept_class_mapper[row["CONCEPT_CLASS"]], 
              })
            elif "OBSERVATION_SOURCE_CONCEPT_ID" in row and row["OBSERVATION_SOURCE_CONCEPT_ID"] is not None:
              out["category"][0]["coding"].append({
                  "system": "http://hl7.org/fhir/ValueSet/observation-category",
                  "code": observation_concept_class_mapper[row["SOURCE_CONCEPT_CLASS"]],
                  "display":  observation_concept_class_mapper[row["SOURCE_CONCEPT_CLASS"]]
              })

            if "OBSERVATION_SOURCE_CONCEPT_ID" in row and row["OBSERVATION_SOURCE_CONCEPT_ID"] != "0" and row["OBSERVATION_SOURCE_CONCEPT_ID"] in vocab_code_to_display:
              out["code"]["coding"][0]["system"] = str(vocab_code_to_display[row["VOCABULARY_SOURCE_CONCEPT_ID"]])
              out["code"]["coding"][0]["code"] =  str(row["SOURCE_CONCEPT_CODE"])
              out["code"]["coding"][0]["display"] = str(row["CONCEPT_NAME"])

            if "QUALIFIER_CONCEPT_ID" in row and row["QUALIFIER_CONCEPT_ID"] is not None:
              out["note"] = [{
                "text": str(int(row["QUALIFIER_CONCEPT_ID"]))
              }]

            if "PROVIDER_ID" in row and row["PROVIDER_ID"] is not None:
              out["performer"] = [{"reference":"Practitioner/" + str(row["practitioner_id"])}]
              out["identifier"].append({
                "system": "https://github.com/OHDSI/Eunomia",
                "value": "Practitioner/" + str(row["PROVIDER_ID"])
              })

            if "VISIT_OCCURRENCE_ID" in row and row["VISIT_OCCURRENCE_ID"] is not None:
              out["encounter"] = {"reference": "Encounter/" + str(row["encounter_id"])} 
              out["identifier"].append({
                "system": "https://github.com/OHDSI/Eunomia",
                "value": "Encounter/" + str(row["VISIT_OCCURRENCE_ID"])
              })

            # Just going to call visit_detail an encounter for now
            # since encounters can reference other encounters
            # TODO: This has to be an extension if there is already a visit occurrence id referenced
            if "visit_detail_id" in row and row["visit_detail_id"] is not None:
                out["identifier"].append({
                  "system": "https://github.com/OHDSI/Eunomia",
                  "value": "Encounter/" + str(row["visit_detail_id"])
                })

            extensions = ["OBSERVATION_SOURCE_VALUE","UNIT_SOURCE_VALUE","QUALIFIER_SOURCE_VALUE"]
            for value in extensions:
              if(value in row and row[value] is not None):
                if(is_int(row[value])):
                  out["extension"].append({
                    "url":"http://hl7.org/fhir/StructureDefinition/#OBSERVATION" + "__" + value,
                    "valueInteger": int(row[value])
                  })
                else:
                  out["extension"].append({
                      "url":"https://ohdsi.github.io/CommonDataModel/cdm54.html#OBSERVATION" + "__" + value,
                      "valueString": str(row[value])
                  })
            if "unit_concept_id" in row and row["unit_concept_id"] is not None:
              out["valueQuantity"] = row["unit_concept_id"]

            hits = 0
            if "value_as_number" in row and row["value_as_number"] is not None:
              out["valueInteger"] = row["value_as_number"]
              hits += 1
            
            elif "value_as_string" in row and row["value_as_string"] is not None:
              out["valueString"] = row["value_as_string"]
              hits += 1

            # this one needs to get mapped to a concept_code but for now since there isn't any actual data for it
            # it will remain how it is
            elif "value_as_concept_id" in row and row["value_as_concept_id"] is not None:
              out["valueCodeableConcept"] = {
                'coding': 
                  [{
                    'system': "https://www.hl7.org/fhir/structuredefinition-value_as_concept_id",
                    'code': str(row["value_as_concept_id"]),
                    'display': str(row["value_as_concept_id"])
                  }]
              }
              hits +=1
            if hits > 1:
              raise Exception("value_as_string, value_as_concept_id and value_as_number as mutually exclusive fields yet there are multiple of them present in this row")

            if len(out["extension"]) == 0:
              del(out["extension"])

            return out
    
    # this is disabled because the row ID does not match the regex [ \\r\\n\\t\\S]+
    # it will go away when the uuids are added
    #- objectValidate:
        #schema: "{{config.schema}}"
        #title: Observation
        
    - emit:
        name: Observation



            

            
